CardTypes = {
    Artifact = 'Artifact',
    Creature = 'Creature',
    Enchantment = 'Enchantment',
    Instant = 'Instant',
    Land = 'Land',
    Planeswalker = 'Planeswalker',
    Sorcery = 'Sorcery',
    Kindred = 'Kindred',
    Dungeon = 'Dungeon',
    Battle = 'Battle',
    Phenomenon = 'Phenomenon',
    Vanguard = 'Vanguard',
    Conspiracy = 'Conspiracy',
}